export interface NbaTeam {
  name: string;
  abbrev: string;
  city: string;
  logo: string;
  primaryColor: string;
  secondaryColor: string;
}

// Logo URLs from cdn.nba.com (official NBA CDN)
const NBA_TEAMS: Record<string, NbaTeam> = {
  "Atlanta Hawks": {
    name: "Atlanta Hawks",
    abbrev: "ATL",
    city: "Atlanta, GA",
    logo: "https://cdn.nba.com/logos/nba/1610612737/global/L/logo.svg",
    primaryColor: "#E03A3E",
    secondaryColor: "#C1D32F",
  },
  "Boston Celtics": {
    name: "Boston Celtics",
    abbrev: "BOS",
    city: "Boston, MA",
    logo: "https://cdn.nba.com/logos/nba/1610612738/global/L/logo.svg",
    primaryColor: "#007A33",
    secondaryColor: "#BA9653",
  },
  "Brooklyn Nets": {
    name: "Brooklyn Nets",
    abbrev: "BKN",
    city: "Brooklyn, NY",
    logo: "https://cdn.nba.com/logos/nba/1610612751/global/L/logo.svg",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
  },
  "Charlotte Hornets": {
    name: "Charlotte Hornets",
    abbrev: "CHA",
    city: "Charlotte, NC",
    logo: "https://cdn.nba.com/logos/nba/1610612766/global/L/logo.svg",
    primaryColor: "#1D1160",
    secondaryColor: "#00788C",
  },
  "Chicago Bulls": {
    name: "Chicago Bulls",
    abbrev: "CHI",
    city: "Chicago, IL",
    logo: "https://cdn.nba.com/logos/nba/1610612741/global/L/logo.svg",
    primaryColor: "#CE1141",
    secondaryColor: "#000000",
  },
  "Cleveland Cavaliers": {
    name: "Cleveland Cavaliers",
    abbrev: "CLE",
    city: "Cleveland, OH",
    logo: "https://cdn.nba.com/logos/nba/1610612739/global/L/logo.svg",
    primaryColor: "#860038",
    secondaryColor: "#041E42",
  },
  "Dallas Mavericks": {
    name: "Dallas Mavericks",
    abbrev: "DAL",
    city: "Dallas, TX",
    logo: "https://cdn.nba.com/logos/nba/1610612742/global/L/logo.svg",
    primaryColor: "#00538C",
    secondaryColor: "#002B5E",
  },
  "Denver Nuggets": {
    name: "Denver Nuggets",
    abbrev: "DEN",
    city: "Denver, CO",
    logo: "https://cdn.nba.com/logos/nba/1610612743/global/L/logo.svg",
    primaryColor: "#0E2240",
    secondaryColor: "#FEC524",
  },
  "Detroit Pistons": {
    name: "Detroit Pistons",
    abbrev: "DET",
    city: "Detroit, MI",
    logo: "https://cdn.nba.com/logos/nba/1610612765/global/L/logo.svg",
    primaryColor: "#C8102E",
    secondaryColor: "#1D42BA",
  },
  "Golden State Warriors": {
    name: "Golden State Warriors",
    abbrev: "GSW",
    city: "San Francisco, CA",
    logo: "https://cdn.nba.com/logos/nba/1610612744/global/L/logo.svg",
    primaryColor: "#1D428A",
    secondaryColor: "#FFC72C",
  },
  "Houston Rockets": {
    name: "Houston Rockets",
    abbrev: "HOU",
    city: "Houston, TX",
    logo: "https://cdn.nba.com/logos/nba/1610612745/global/L/logo.svg",
    primaryColor: "#CE1141",
    secondaryColor: "#000000",
  },
  "Indiana Pacers": {
    name: "Indiana Pacers",
    abbrev: "IND",
    city: "Indianapolis, IN",
    logo: "https://cdn.nba.com/logos/nba/1610612754/global/L/logo.svg",
    primaryColor: "#002D62",
    secondaryColor: "#FDBB30",
  },
  "Los Angeles Clippers": {
    name: "Los Angeles Clippers",
    abbrev: "LAC",
    city: "Los Angeles, CA",
    logo: "https://cdn.nba.com/logos/nba/1610612746/global/L/logo.svg",
    primaryColor: "#C8102E",
    secondaryColor: "#1D428A",
  },
  "Los Angeles Lakers": {
    name: "Los Angeles Lakers",
    abbrev: "LAL",
    city: "Los Angeles, CA",
    logo: "https://cdn.nba.com/logos/nba/1610612747/global/L/logo.svg",
    primaryColor: "#552583",
    secondaryColor: "#FDB927",
  },
  "Memphis Grizzlies": {
    name: "Memphis Grizzlies",
    abbrev: "MEM",
    city: "Memphis, TN",
    logo: "https://cdn.nba.com/logos/nba/1610612763/global/L/logo.svg",
    primaryColor: "#5D76A9",
    secondaryColor: "#12173F",
  },
  "Miami Heat": {
    name: "Miami Heat",
    abbrev: "MIA",
    city: "Miami, FL",
    logo: "https://cdn.nba.com/logos/nba/1610612748/global/L/logo.svg",
    primaryColor: "#98002E",
    secondaryColor: "#F9A01B",
  },
  "Milwaukee Bucks": {
    name: "Milwaukee Bucks",
    abbrev: "MIL",
    city: "Milwaukee, WI",
    logo: "https://cdn.nba.com/logos/nba/1610612749/global/L/logo.svg",
    primaryColor: "#00471B",
    secondaryColor: "#EEE1C6",
  },
  "Minnesota Timberwolves": {
    name: "Minnesota Timberwolves",
    abbrev: "MIN",
    city: "Minneapolis, MN",
    logo: "https://cdn.nba.com/logos/nba/1610612750/global/L/logo.svg",
    primaryColor: "#0C2340",
    secondaryColor: "#236192",
  },
  "New Orleans Pelicans": {
    name: "New Orleans Pelicans",
    abbrev: "NOP",
    city: "New Orleans, LA",
    logo: "https://cdn.nba.com/logos/nba/1610612740/global/L/logo.svg",
    primaryColor: "#0C2340",
    secondaryColor: "#C8102E",
  },
  "New York Knicks": {
    name: "New York Knicks",
    abbrev: "NYK",
    city: "New York, NY",
    logo: "https://cdn.nba.com/logos/nba/1610612752/global/L/logo.svg",
    primaryColor: "#006BB6",
    secondaryColor: "#F58426",
  },
  "Oklahoma City Thunder": {
    name: "Oklahoma City Thunder",
    abbrev: "OKC",
    city: "Oklahoma City, OK",
    logo: "https://cdn.nba.com/logos/nba/1610612760/global/L/logo.svg",
    primaryColor: "#007AC1",
    secondaryColor: "#EF6020",
  },
  "Orlando Magic": {
    name: "Orlando Magic",
    abbrev: "ORL",
    city: "Orlando, FL",
    logo: "https://cdn.nba.com/logos/nba/1610612753/global/L/logo.svg",
    primaryColor: "#0077C0",
    secondaryColor: "#C4CED4",
  },
  "Philadelphia 76ers": {
    name: "Philadelphia 76ers",
    abbrev: "PHI",
    city: "Philadelphia, PA",
    logo: "https://cdn.nba.com/logos/nba/1610612755/global/L/logo.svg",
    primaryColor: "#006BB6",
    secondaryColor: "#ED174C",
  },
  "Phoenix Suns": {
    name: "Phoenix Suns",
    abbrev: "PHX",
    city: "Phoenix, AZ",
    logo: "https://cdn.nba.com/logos/nba/1610612756/global/L/logo.svg",
    primaryColor: "#1D1160",
    secondaryColor: "#E56020",
  },
  "Portland Trail Blazers": {
    name: "Portland Trail Blazers",
    abbrev: "POR",
    city: "Portland, OR",
    logo: "https://cdn.nba.com/logos/nba/1610612757/global/L/logo.svg",
    primaryColor: "#E03A3E",
    secondaryColor: "#000000",
  },
  "Sacramento Kings": {
    name: "Sacramento Kings",
    abbrev: "SAC",
    city: "Sacramento, CA",
    logo: "https://cdn.nba.com/logos/nba/1610612758/global/L/logo.svg",
    primaryColor: "#5A2D81",
    secondaryColor: "#63727A",
  },
  "San Antonio Spurs": {
    name: "San Antonio Spurs",
    abbrev: "SAS",
    city: "San Antonio, TX",
    logo: "https://cdn.nba.com/logos/nba/1610612759/global/L/logo.svg",
    primaryColor: "#C4CED4",
    secondaryColor: "#000000",
  },
  "Toronto Raptors": {
    name: "Toronto Raptors",
    abbrev: "TOR",
    city: "Toronto, ON",
    logo: "https://cdn.nba.com/logos/nba/1610612761/global/L/logo.svg",
    primaryColor: "#CE1141",
    secondaryColor: "#000000",
  },
  "Utah Jazz": {
    name: "Utah Jazz",
    abbrev: "UTA",
    city: "Salt Lake City, UT",
    logo: "https://cdn.nba.com/logos/nba/1610612762/global/L/logo.svg",
    primaryColor: "#002B5C",
    secondaryColor: "#00471B",
  },
  "Washington Wizards": {
    name: "Washington Wizards",
    abbrev: "WAS",
    city: "Washington, DC",
    logo: "https://cdn.nba.com/logos/nba/1610612764/global/L/logo.svg",
    primaryColor: "#002B5C",
    secondaryColor: "#E31837",
  },
};

export function getTeam(name: string): NbaTeam {
  return (
    NBA_TEAMS[name] ?? {
      name,
      abbrev: name.slice(0, 3).toUpperCase(),
      city: "",
      logo: "",
      primaryColor: "#6b7280",
      secondaryColor: "#374151",
    }
  );
}

export default NBA_TEAMS;
